org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Check https://fabricmc.net/develop for the exact current values for 26.1.2
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_version=0.161.0+26.3

mod_version=1.0.0
maven_group=com.example
archives_base_name=macrorecorder
